### ISSUE TITLE
Disable `wakubridge` on `status.prod` fleets

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-status-legacy#14]
## Problem

After discussion with Status product teams, they seem to be having store query performance issues on the fleets while trying to dogfood Waku v2 integration. While investigation into the performance issues is underway, one way to unblock dogfooding is to disable the wakubridge on the fleets and clear the existing history (`Message` table in existing sqlite DBs). We have decided to do this only on the Status prod fleet(s) (both go-waku and nwaku) and _not_ on the test fleets.

## Summary:

- [x] disable `wakubridge` on the `status.prod` fleets (apparently there is both a go-waku and nwaku `prod` fleet for Status?)
- [x] clear the `Message` table on each of the store nodes and restart

cc @jakubgs

**Comment by jakubgs** [comment]
I have disabled connecting the bridge node to the `statu.sprod` fleet peers: https://github.com/status-im/infra-status/commit/74f980b9
https://github.com/status-im/infra-status/blob/74f980b9565de4186a8113114d66c8aca872cd0c/ansible/group_vars/status.yml#L44-L47
Deployed the changes, and purge the DB, since the `Peer` table also needed to be cleared to forge the bridge node.

Anything else @jm-clius ?

**Comment by jm-clius** [comment]
No, thanks @jakubgs, afaict the bridge has now been successfully disconnected on `prod` and clearing the DBs would have been enough. Closing as resolved.
