### ISSUE TITLE
Missing trace logs on prod nodes

### ISSUE THREAD

**Issue by vitvly** [status-im/infra-status-legacy#36]
When checking Kibana i don't see "waku.relay published" logs that are supposed to be printed with this line:

https://github.com/waku-org/nwaku/blob/6d81e3841afea2ae20969e26ecf9a4b64bbb4d1d/waku/node/waku_node.nim#L328

So it seems that tracing logs are still not enabled.

cc @jakubgs @jm-clius @cammellos

**Comment by alrevuelta** [comment]
afaik that TRACE log is enabled with an env variable at compile time. Meaning that you can have TRACE logs enabled but if you haven't compiled with that flag, then this log wont be showing up (but the rest of TRACE will do)

in any case, you should not run with TRACE in prod, since it will impact a lot the performance.

**Comment by jm-clius** [comment]
> afaik that TRACE log is enabled with an env variable at compile time

Afaict it's still [a normal trace log as it was before](https://github.com/waku-org/nwaku/tree/master/waku/waku_core#L199-L210) and the `traceHandler` is not beyond a compiler variable: https://github.com/waku-org/nwaku/blob/c973b8506922a1924abe5ad03d130ab36928c44d/waku/node/waku_node.nim#L199-L210

> in any case, you should not run with TRACE in prod

The infra team does compile an image with only this log topic included for a single debug node in each fleet. It does log on trace level, but it only logs the relayed messages - not any other trace logs.

**Comment by jakubgs** [comment]
The trace logs are definitely enabled:
https://github.com/status-im/infra-status/blob/c32c7528230177d89e73762fab64c40667cfe6f8/ansible/host_vars/node-02.do-ams3.status.prod.yml#L2-L5
And on the host as well:
```
admin@node-02.do-ams3.status.prod:~ % grep level /docker/nim-waku/docker-compose.yml
      --log-level=TRACE
```
And the log files do contain `waku.relay received`  messages:
```
admin@node-02.do-ams3.status.prod:~ % zgrep 'waku.relay received' /var/log/docker/nim-waku/docker.* | wc -l
118303

admin@node-02.do-ams3.status.prod:~ % zgrep 'waku.relay received' /var/log/docker/nim-waku/docker.* | head -n1
/var/log/docker/nim-waku/docker.log:2023-11-21T13:09:24.085052+00:00 docker/nim-waku[6704]: TRC 2023-11-21 13:09:24.084+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:199 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0x8207da716ac14d99a0b405a9e9241de28cc9c94c5f1f60ce5be35b09aae59fb1 receivedTime=1700572164084689408 payloadSizeBytes=540

admin@node-02.do-ams3.status.prod:~ % zgrep 'waku.relay received' /var/log/docker/nim-waku/docker.* | tail -n1
/var/log/docker/nim-waku/docker.log:2023-11-21T16:58:35.145127+00:00 docker/nim-waku[6704]: TRC 2023-11-21 16:58:35.144+00:00 waku.relay received                        topics="waku node" tid=1 file=waku_node.nim:199 peerId=16U*TCnsXV pubsubTopic=/waku/2/default-waku/proto hash=0xb08ffcd4efc4e7ccbc0c13489bc51d0a71c8988d90e2c5c37d06a40a9459a583 receivedTime=1700585915144766464 payloadSizeBytes=1052
```
They appear to start on `2023-11-21T13:09:24` and end on `2023-11-21T16:58:35`.

And are visible in Kibana:

![image](https://github.com/status-im/infra-status/assets/2212681/6efc68e8-3e56-426b-9451-f7c9e1952f49)
https://kibana.infra.status.im/goto/7ab3ab00-888f-11ee-aaa4-85391103106b

The only reason they weren't visible before was because Waku nodes stop working for hours after restarts if vacuuming is enabled, which I have disabled today:

- [`infra-status#e16ca12e`](https://github.com/status-im/infra-status/commit/e16ca12e) - status: disable store DB vacuuming

Fortunately we will be switching this fleet to PostgreSQL soon:

* https://github.com/status-im/infra-status/issues/37
