### ISSUE TITLE
Enable DiscV5 in status.test and status.prod

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-status-legacy#6]
The following options must be set on status.test and status.prod fleets:
```
--discv5-discovery=true
--discv5-udp-port=9000 (or change it to some other value)         Listening UDP port for Node Discovery v5. [=9000].
--discv5-bootstrap-node   Text-encoded ENR for bootstrap node. Used when connecting to the network. Argument may be repeated..
--discv5-enr-auto-update=true
```
cc: @iurimatias @jm-clius

**Comment by jakubgs** [comment]
But what should be the bootstrap nodes?

**Comment by richard-ramos** [comment]
Not sure. They're supposed to be bootstrap nodes themselves. Maybe that value should be empty? or the option not set at all?

**Comment by jakubgs** [comment]
@jm-clius would it be fine to enable this by default on all nodes? Or should it be kept just to `status.*` fleets?

**Comment by jm-clius** [comment]
I think it's best if we enable them only on the `status.*` fleets, just to see how it grows.
@kaiserd, am I right in saying that `--discv5-bootstrap-node` can remain unset for the fleet nodes? They will themselves serve as bootstrap nodes, are already connected to each other and we don't (currently) want them to have the other fleet nodes in their routing table.
I think it's possible that nodes could "leak" between networks if we're not careful (@kaiserd what do you think the chances or of this happening?), though the impact would likely be contained between the `status.*` fleets as they currently route roughly the same traffic.

**Comment by jakubgs** [comment]
Done:

- https://github.com/status-im/infra-status/commit/943fb68c - enable Discovery V5 for all status nodes
- https://github.com/status-im/infra-role-nim-waku/commit/1e5367c8 - add support for Discovery V5 flags

https://github.com/status-im/infra-status/blob/943fb68c7023855c3e2f812906c550c48f2a809a/ansible/group_vars/status.yml#L21-L24
```
 > a status -a 'grep discv5 /docker/nim-waku/docker-compose.yml'                                                   
node-01.do-ams3.status.test | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-01.gc-us-central1-a.status.test | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-01.ac-cn-hongkong-c.status.test | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
```
Will roll out to `prod` later if nothing breaks.

**Comment by kaiserd** [comment]
> I think it's best if we enable them only on the status.* fleets, just to see how it grows.

agreed

> @kaiserd, am I right in saying that --discv5-bootstrap-node can remain unset for the fleet nodes? 

Yes.  As soon as other nodes use the fleet nodes as bootstrap nodes, the routing tables of the bootstrap nodes will fill up.

> we don't (currently) want them to have the other fleet nodes in their routing table.

The will most likely discover each other.
Later, imo, it would make sense to provide the respective other fleet nodes to each fleet node as bootstrap nodes, because this improves resilience of the network in the launching phase.


> I think it's possible that nodes could "leak" between networks if we're not careful (@kaiserd what do you think the chances or of this happening?)

Leakage could happen if a non-waku discv5 node puts a `nwaku` node in its routing table and does not check the `protocol-id`, for instance because the `nwaku` node was wrongly provided as a bootstrap node.
In this case, the `nwaku` node would receive a few queries... but because it does not answer to queries with a `protocol-id != d5waku`, it would not answer. This in turn should cause the `nwaku` node to be removed from this routing table in due time.
If `nwaku` nodes query non-waku nodes, the responses will not be accepted in the first place because `nwaku` checks the `protocol-id`.
So, I expect the effects of (accidental) leakage to be very small.
Still, I might have overlooked something and I agree it is a good idea to deploy discv5 only on the `status.*` fleets for now.

**Comment by kaiserd** [comment]
Maybe it would also make sense now to list the ENRs of the [fleet nodes](https://fleets.status.im/), so that Waku2 nodes can bootstrap discv5.
(Alternatively, the respective `entree://` DNS discovery domain would be enough after we release the next version, which features DNS bootstrap for discv5.)

**Comment by jakubgs** [comment]
I've deployed the changes to `status.prod`:
```
 > a status -a 'grep discv5 /docker/nim-waku/docker-compose.yml'
node-01.do-ams3.status.prod | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-02.do-ams3.status.prod | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-02.gc-us-central1-a.status.prod | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-01.gc-us-central1-a.status.prod | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-02.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
node-01.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 >>
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=True
```
